# Generated by Django 3.2 on 2023-10-11 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InputFiles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='research/potential')),
                ('file_result', models.CharField(max_length=218, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='input_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'inputfile',
                'verbose_name_plural': 'inputfiles',
                'ordering': ['-id'],
            },
        ),
    ]
