# Generated by Django 3.2 on 2023-10-10 10:52

import cms.models.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import elearning.apps.core.fields
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0005_auto_20220424_2025'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, default=10000)),
                ('slug', models.SlugField(max_length=250, null=True)),
                ('full_bio', cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='full_bio', slotname='partner_full_bio', to='cms.placeholder')),
                ('institution', models.ManyToManyField(blank=True, related_name='institution_instructors', to='users.Institution')),
                ('short_bio', cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='short_bio', slotname='partner_short_bio', to='cms.placeholder')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', elearning.apps.core.fields.OrderField(blank=True, default=1)),
                ('title', models.CharField(default='', max_length=128)),
                ('publisher', models.CharField(default='', max_length=128)),
                ('year', models.SmallIntegerField(default='2020')),
                ('citation', models.CharField(default='', max_length=256)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='partners.instructors')),
            ],
            options={
                'ordering': ['-year', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', elearning.apps.core.fields.OrderField(blank=True, default=1)),
                ('organization_name', models.CharField(default='', max_length=128)),
                ('address1', models.CharField(blank=True, max_length=128, null=True)),
                ('address2', models.CharField(blank=True, max_length=128, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(default='', max_length=128)),
                ('country', models.CharField(default='', max_length=128)),
                ('office_phone', models.CharField(default='', max_length=128)),
                ('cell_phone', models.CharField(default='', max_length=128)),
                ('owner_image', models.ImageField(blank=True, null=True, upload_to='partners/%Y/%m/%d/')),
                ('organization_image', models.ImageField(blank=True, null=True, upload_to='partners/%Y/%m/%d/')),
                ('slug', models.SlugField(max_length=250, null=True)),
                ('description', cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname='partner_description', to='cms.placeholder')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
