# Generated by Django 3.2 on 2023-10-18 13:28

import cms.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('cms', '0022_auto_20180620_1551'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, default=1000, null=True)),
                ('institution_name', models.CharField(blank=True, max_length=100, null=True)),
                ('welcome_phrase_title', models.CharField(blank=True, max_length=200, null=True)),
                ('welcome_phrase_title_description', models.CharField(blank=True, max_length=1000, null=True)),
                ('institution_image', models.ImageField(blank=True, null=True, upload_to='institution/')),
                ('institution_logo_image', models.ImageField(blank=True, null=True, upload_to='institution/')),
                ('join_us_title', models.CharField(blank=True, default='black', max_length=100, null=True)),
                ('course_header', models.CharField(blank=True, max_length=100, null=True)),
                ('course_description_one', models.CharField(blank=True, max_length=1000, null=True)),
                ('course_description_two', models.CharField(blank=True, max_length=1000, null=True)),
                ('category_header', models.CharField(blank=True, max_length=100, null=True)),
                ('category_description_one', models.CharField(blank=True, max_length=1000, null=True)),
                ('category_description_two', models.CharField(blank=True, max_length=1000, null=True)),
                ('event_header', models.CharField(blank=True, max_length=100, null=True)),
                ('event_description_one', models.CharField(blank=True, max_length=1000, null=True)),
                ('event_description_two', models.CharField(blank=True, max_length=1000, null=True)),
                ('section_two_header', models.CharField(blank=True, max_length=100, null=True)),
                ('section_two_description_one', models.CharField(blank=True, max_length=1000, null=True)),
                ('section_two_description_two', models.CharField(blank=True, max_length=1000, null=True)),
                ('section_two_image', models.ImageField(blank=True, null=True, upload_to='institution/')),
                ('section_three_header', models.CharField(blank=True, max_length=100, null=True)),
                ('section_three_description_one', models.CharField(blank=True, max_length=1000, null=True)),
                ('section_three_description_two', models.CharField(blank=True, max_length=1000, null=True)),
                ('section_three_image', models.ImageField(blank=True, null=True, upload_to='institution/')),
                ('introduction_phrase_color', models.CharField(blank=True, default='black', max_length=100, null=True)),
                ('searching_title', models.CharField(blank=True, max_length=100, null=True)),
                ('search_explore_catalog_title', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'institution',
                'verbose_name_plural': 'institutions',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, default=1000)),
                ('fee', models.CharField(default='0', max_length=30, null=True)),
                ('course_name', models.CharField(max_length=100, null=True)),
                ('number_of_registered_students_for_the_course', models.IntegerField(blank=True, default=0)),
                ('course_image', models.CharField(max_length=100, null=True)),
                ('is_popular', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(default=21, on_delete=django.db.models.deletion.CASCADE, related_name='course_courses', to='courses.course')),
                ('description', cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='education_course_description', slotname='description', to='cms.placeholder')),
                ('institution_web', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='partners.institutionweb')),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
                'ordering': ['order'],
            },
        ),
    ]
