# Generated by Django 3.2 on 2023-10-19 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_alter_course_course_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institutionweb',
            name='introduction_phrase_color',
        ),
        migrations.RemoveField(
            model_name='institutionweb',
            name='search_explore_catalog_title',
        ),
        migrations.RemoveField(
            model_name='institutionweb',
            name='searching_title',
        ),
        migrations.AddField(
            model_name='institutionweb',
            name='institution_motion_image',
            field=models.ImageField(blank=True, null=True, upload_to='institution/'),
        ),
        migrations.AlterField(
            model_name='institutionweb',
            name='join_us_title',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
