# Generated by Django 3.2 on 2023-10-19 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_auto_20231019_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionweb',
            name='section_two_motion_image',
            field=models.ImageField(blank=True, null=True, upload_to='institution/'),
        ),
    ]
