# Generated by Django 3.2 on 2023-10-19 07:40

import cms.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('partners', '0005_institutionweb_section_two_motion_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, default=1000)),
                ('program_image', models.ImageField(blank=True, null=True, upload_to='Programs/')),
                ('program_name', models.CharField(max_length=100, null=True)),
                ('program_description', models.CharField(max_length=500, null=True)),
                ('program_link_title', models.CharField(max_length=500, null=True)),
                ('is_popular', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program_description', slotname='description', to='cms.placeholder')),
                ('institution_web', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='partners.institutionweb')),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
                'ordering': ['order'],
            },
        ),
    ]
