# Generated by Django 3.2 on 2023-10-19 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0006_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonsPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, default=1000)),
                ('persons_phrase_image', models.ImageField(blank=True, null=True, upload_to='phrase/')),
                ('persons_phrase', models.CharField(max_length=500, null=True)),
                ('persons_name', models.CharField(max_length=500, null=True)),
                ('persons_job_title', models.CharField(max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('institution_web', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='phrases', to='partners.institutionweb')),
            ],
            options={
                'verbose_name': 'phrase',
                'verbose_name_plural': 'phrases',
                'ordering': ['order'],
            },
        ),
    ]
