# Generated by Django 3.2 on 2023-10-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0008_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_links',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='personsphrase',
            name='is_links',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='program',
            name='is_links',
            field=models.BooleanField(default=True),
        ),
    ]
