# Generated by Django 3.2 on 2023-10-19 10:03

import cms.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('partners', '0009_auto_20231019_0931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, default=1000)),
                ('event_image', models.ImageField(blank=True, null=True, upload_to='event/')),
                ('event_date', models.DateField(blank=True, null=True)),
                ('event_name', models.CharField(blank=True, max_length=50, null=True)),
                ('event_location', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_links', models.BooleanField(default=True)),
                ('description', cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_description', slotname='description', to='cms.placeholder')),
                ('institution_web', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='partners.institutionweb')),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
                'ordering': ['order'],
            },
        ),
    ]
