# Generated by Django 3.2 on 2023-10-19 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0010_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyUS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, default=1000)),
                ('description', models.DateField(blank=True, null=True)),
                ('icon_name', models.CharField(blank=True, max_length=50, null=True)),
                ('institution_web', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='whyuses', to='partners.institutionweb')),
            ],
            options={
                'verbose_name': 'whyus',
                'verbose_name_plural': 'whyuses',
                'ordering': ['order'],
            },
        ),
    ]
