# Generated by Django 3.2 on 2023-10-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0011_whyus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whyus',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
