# Generated by Django 3.2 on 2023-10-19 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('partners', '0012_alter_whyus_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_schedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='course_course_schedule', to='courses.courseschedule'),
        ),
    ]
