# Generated by Django 3.2 on 2023-11-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0013_course_course_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='program_description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
