# Generated by Django 3.2 on 2023-11-09 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0014_course_program_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='program_description',
            new_name='course_description',
        ),
    ]
