# Generated by Django 3.2 on 2023-11-10 09:16

import cms.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('partners', '0015_rename_program_description_course_course_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, default=1000)),
                ('service_image', models.ImageField(blank=True, null=True, upload_to='service/')),
                ('service_name', models.CharField(max_length=100, null=True)),
                ('service_description', models.CharField(max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_description', slotname='description', to='cms.placeholder')),
                ('institution_web', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='partners.institutionweb')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order'],
            },
        ),
    ]
