# Generated by Django 3.2 on 2023-11-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0016_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='is_links',
            field=models.BooleanField(default=True),
        ),
    ]
