# Generated by Django 3.2 on 2023-11-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0017_services_is_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
