# Generated by Django 3.2 on 2023-11-10 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0018_event_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionweb',
            name='standalone_section_description_one',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='institutionweb',
            name='standalone_section_description_two',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='institutionweb',
            name='standalone_section_image',
            field=models.ImageField(blank=True, null=True, upload_to='institution/'),
        ),
    ]
