# Generated by Django 3.2 on 2023-11-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0019_auto_20231110_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionweb',
            name='about_us_description_one',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='institutionweb',
            name='about_us_description_two',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='institutionweb',
            name='about_us_header_one',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='institutionweb',
            name='about_us_header_two',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='institutionweb',
            name='about_us_image',
            field=models.ImageField(blank=True, null=True, upload_to='institution/about/'),
        ),
    ]
