# Generated by Django 3.2 on 2023-11-10 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0020_auto_20231110_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='whyus',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='whyus',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
