# Generated by Django 3.2 on 2023-11-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0022_receivedmessages'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionweb',
            name='email',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
