# Generated by Django 3.2 on 2023-11-13 11:23

import cms.models.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('partners', '0023_institutionweb_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionweb',
            name='description',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_institution_web_description', slotname='description', to='cms.placeholder'),
        ),
    ]
