# Generated by Django 3.2 on 2023-10-11 15:58

from django.db import migrations, models
import django.db.models.deletion
import elearning.apps.core.sql


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adjectives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DataAdvancedApps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(default='app_name', max_length=50, null=True)),
                ('app_content', models.JSONField(null=True)),
            ],
            options={
                'verbose_name': 'DataAdvancedApps',
                'verbose_name_plural': 'DataAdvancedApps',
            },
        ),
        migrations.CreateModel(
            name='DataAdvancedTabs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_name', models.CharField(default='tab', max_length=50, null=True)),
                ('tab_content', models.JSONField(null=True)),
                ('order', models.SmallIntegerField(blank=True, default=1)),
            ],
            options={
                'verbose_name': 'DataAdvancedTabs',
                'verbose_name_plural': 'DataAdvancedTabs',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DataAdvancedTabsManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_name', models.CharField(default='new', max_length=50, null=True)),
                ('manager_content', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Debug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=1024)),
            ],
            bases=(elearning.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='GeneralData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('group', models.CharField(blank=True, default='general', max_length=40, null=True)),
                ('data_name', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('data_json', models.JSONField(null=True)),
            ],
            options={
                'verbose_name': 'general_data',
                'verbose_name_plural': 'general_datas',
                'ordering': ['app', 'group', 'data_name'],
            },
            bases=(elearning.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='InstitutionWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, default=1000, null=True)),
                ('institution_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'verbose_name': 'institution',
                'verbose_name_plural': 'institutions',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Numbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.IntegerField(choices=[(0, 'Other'), (1, 'General Ledger')], default=1)),
                ('number', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ReceivedMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.CharField(blank=True, default='', max_length=100)),
                ('subject', models.CharField(blank=True, default='', max_length=100)),
                ('message', models.CharField(blank=True, default='', max_length=2000)),
                ('institution_web', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='core.institutionweb')),
            ],
            options={
                'verbose_name': 'received_message',
                'verbose_name_plural': 'received_messages',
            },
        ),
        migrations.CreateModel(
            name='DataAdvancedTabsCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_content', models.JSONField(null=True)),
                ('tab', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.dataadvancedtabs')),
            ],
        ),
        migrations.AddField(
            model_name='dataadvancedtabs',
            name='manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.dataadvancedtabsmanager'),
        ),
        migrations.CreateModel(
            name='AdjectivesValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.SmallIntegerField(blank=True, default=1)),
                ('value', models.CharField(max_length=50)),
                ('adjective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.adjectives')),
            ],
        ),
    ]
