# Generated by Django 3.2 on 2023-11-17 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_rename_user_userprofile_user_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_profile',
            new_name='user',
        ),
    ]
