# Generated by Django 3.2 on 2023-11-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_rename_user_profile_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='customer_profile',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
