# Generated by Django 3.2 on 2023-11-17 10:53

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('marketplace', '0004_userprofile_customer_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('customer_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='marketplace.userprofile')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
