# Generated by Django 3.2 on 2023-11-17 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
        ('users', '0003_remove_profile_customer_name'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('cms', '0022_auto_20180620_1551'),
        ('partners', '0024_institutionweb_description'),
        ('courses', '0001_initial'),
        ('socialaccount', '0001_initial'),
        ('account', '0001_initial'),
        ('actions', '0001_initial'),
        ('filer', '0017_image__transparent'),
        ('marketplace', '0005_globuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='customer_profile',
        ),
        migrations.DeleteModel(
            name='GlobUser',
        ),
    ]
