# Generated by Django 3.2 on 2023-11-17 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_customer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='customer_name',
        ),
    ]
